#!/bin/bash

set -o nounset
set -o errexit

FILE=$1
VERSION=$2

docker run \
	--tty \
	--env AWS_ACCESS_KEY=${AWS_ACCESS_KEY} \
	--env AWS_SECRET_KEY=${AWS_SECRET_KEY} \
	--volume "$(pwd)/$(dirname ${FILE}):/dist:ro" \
  bioboxes/file-deployer \
	bioboxes-tools validate-binning ${VERSION} /dist/bioboxes-binning
